### PR TITLE
372 time selector

### LINKED ISSUE #372: Show Calendar - [Spike] Time Selector
Look into if there are better time selectors than the standard form type="time" input, or modifying the default behavior with redux-form

The current input:
- Can be completely cleared using the delete key or putting an invalid number
- Selection is difficult when trying to change time, can only use arrow keys or re-enter numbers manually.
- Field level validation is not working, however should not be required if the delete on the input is completely disabled.

Examples: 
https://react-component.github.io/time-picker/
https://www.npmjs.com/package/react-times
https://reactjsexample.com/simple-react-time-input-field/

### PR DESCRIPTION
**Pull request by jberns**
## Guidelines

DEVELOPMENT branch on the LEFT <br>
YOUR branch on the RIGHT

## Issue

This issue resolves #372, #465 

## Description

This pull requests addresses the following items:
1) Added a new date picker component to handle both date and time of the show start and end times
2) Updated the show query to populate the master data instead of using async await later (similar to table join at the start)
3) Updated repeat end date calculation for when UTC was midnight, subtracted 1 minute instead of trying to set the hours/minutes on the day.

### CODE REVIEW

File: client/src/components/DatePicker/index.js [hunk 1]
```diff
@@ -1 +1,2 @@
-export { default } from './DatePicker';
+export { default } from './DatePicker__AirBNB';
+export { default as DatePicker__React } from './DatePicker__React';
```
Comment (seankwilliams) [inline client/src/components/DatePicker/index.js]: nice work here @jberns !
