### PR TITLE
465 api bug fix

### LINKED ISSUE #465: Show find API issues
The show API is not returning the correct values in the following instances:

**http://localhost:3000/v1/shows/?startDate="2019-05-23T14:22:09.544Z"&endDate="2019-05-23T23:22:09.544Z"**

Actual Results: `[]`

Expected Results: Should return the events between 8:22am-5:22pm on 5/23. Let's include events that span over that timeframe, in other words: if an event starts before 8:22am but is active at 8:22am (ie, an 8am-9am event), it should be included in the results. An event that goes from 5pm-5:30pm should also be included.

**http://localhost:3000/v1/shows/?startDate="2019-05-23T14:22:09.544Z"&endDate="2019-05-24T14:22:09.544Z"**

Actual Results: Returns the following Afternoon Sound Alternative object:
```
{
  "show_details": {
      "guests": [
          null
      ],
      "title": "Afternoon Sound Alternative",
      "summary": "Diverse and eclectic sounds on the more adventurous side.",
      "description": "<p>Diverse and eclectic sounds on the more adventurous side. Tune in for everything from Free Jazz to Hip Hop to Cumbia.</p>",
      "producer": null,
      "host": null,
      "custom": {
          "record_audio": "1",
          "url": "afternoonsound",
          "source": "KGNU"
      }
  },
  "repeat_rule": {
      "byweekday": [
          "MO",
          "TU",
          "WE",
          "TH",
          "FR"
      ],
      "repeat_start_date": "2011-03-28T18:06:00.000Z",
      "frequency": 2,
      "repeat_end_date": "9999-01-01T07:00:00.000Z"
  },
  "status": "active",
  "exclude_dates": [
      "2016-07-29T18:06:00.000Z"
  ],
  "_id": "5cf12122f583ec16304b140d-1558721160000",
  "show_start_time_utc": "2019-05-24T18:06:00.000Z",
  "show_end_time_utc": "2019-05-24T21:00:00.000Z",
  "is_recurring": true,
  "created_at": "2019-05-31T12:42:10.647Z",
  "updated_at": "2019-05-31T12:42:10.647Z",
  "__v": 0,
  "master_show_uid": "5cf12122f583ec16304b140d",
  "master_time_id": "5cf12122f583ec16304b140d-1558721160000"
}
```

Expected results: Should be the 5/23 show, not the 5/24 show

**http://localhost:3000/v1/shows/?startDate="2019-05-22T14:22:09.544Z"&endDate="2019-05-23T14:22:09.544Z"**

Actual Results: Afternoon Sound Alternative object is:
```
{
        "show_details": {
            "guests": [
                null
            ],
            "title": "Afternoon Sound Alternative",
            "summary": "Diverse and eclectic sounds on the more adventurous side.",
            "description": "<p>Diverse and eclectic sounds on the more adventurous side. Tune in for everything from Free Jazz to Hip Hop to Cumbia.</p>",
            "producer": null,
            "host": null,
            "custom": {
                "record_audio": "1",
                "url": "afternoonsound",
                "source": "KGNU"
            }
        },
        "repeat_rule": {
            "byweekday": [
                "MO",
                "TU",
                "WE",
                "TH",
                "FR"
            ],
            "repeat_start_date": "2011-03-28T18:06:00.000Z",
            "frequency": 2,
            "repeat_end_date": "9999-01-01T07:00:00.000Z"
        },
        "status": "active",
        "exclude_dates": [
            "2016-07-29T18:06:00.000Z"
        ],
        "_id": "5cf12122f583ec16304b140d-1558634760000",
        "show_start_time_utc": "2019-05-23T18:06:00.000Z",
        "show_end_time_utc": "2019-05-23T21:00:00.000Z",
        "is_recurring": true,
        "created_at": "2019-05-31T12:42:10.647Z",
        "updated_at": "2019-05-31T12:42:10.647Z",
        "__v": 0,
        "master_show_uid": "5cf12122f583ec16304b140d",
        "master_time_id": "5cf12122f583ec16304b140d-1558634760000"
    }
```

Expected Results: Should include the information from the 5/23 show instance (note the differences in `show_details`):
show-details

### PR DESCRIPTION
**Pull request by jberns**
## Guidelines

DEVELOPMENT branch on the LEFT <br>
YOUR branch on the RIGHT

## Issue
This issue resolves #465 

## Description

This pull request fixes the:
1) Shows that are returned when using the get request from from the find API.
2) Fixes the initial date offset of the first show being returned.
3) Returns the proper instance show
4) Merges the master show data with instance data when the instance is missing data from the master show.

### CODE REVIEW

File: client/src/redux/show/showReducer.js [hunk 1]
```diff
@@ -66,8 +66,8 @@ export function showReducer(state = initialState, { type, payload }) {
 
     case SHOW_DELETE:
       let deleteShow = { ...state.data };
-
-      delete deleteShow[payload._id];
+      console.log(payload);
```
Comment (seankwilliams) [inline client/src/redux/show/showReducer.js]: be sure to remove this before merging
